version: 2

sources:
  - name: retail_source
    database: retail-analytics-lakehouse
    schema: retail_raw
    loaded_at_field: updated_timestamp
    freshness:
      warn_after: { count: 24, period: hour }
#      error_after: { count: 24, period: hour }
    tables:
      - name: customers
      - name: employees
      - name: order_items
      - name: orders
      - name: products
      - name: stores
